version: "3"
services:
  redis:
    build: 
        context: ./datasources/redis/
    restart: always
  go-app:
    build: .
    restart: always
    depends_on: 
      - redis
    ports:
      - "8080:8080"