version: "3"
services:
  redis:
    image: shonphand/redis
    restart: always
  go-app:
    image: shonphand/cryptoserver:1.0.1
    restart: always
    depends_on: 
      - redis
    ports:
      - "8080:8080"